compatibility_date = "2023-10-25"
name = "worker-template"
workers_dev = true
routes = []
vars = {}
main = "./dist/_worker.js"
port = 8787

[build]
command = "npm install && npm run build:api"
upload.format = "modules"

[env.production]
workers_dev = false
vars = {}
durable_objects.bindings = []
kv_namespaces = []
r2_buckets = []

[env.local]
workers_dev = true
vars = { adminSecret = "adminSecret", ui = "localhost:3333" }
durable_objects.bindings = []
kv_namespaces = []
r2_buckets = []


[dev]
port = 8787
